### PR TITLE
Create getRankNameInGroup.js

### PR DESCRIPTION
**Pull request by suufi**

### CODE REVIEW

**Review by sentanos — CHANGES_REQUESTED** [review]
Resolve with full body (GetGroupRole does not return XML tags)
Use correct cache

**Comment by sentanos** [comment]
It would actually make sense to leave the Rank cache as it is and not create the RankName cache at all (they are essentially the same thing)

**Comment by OnlyTwentyCharacters** [comment]
Updated.

**Comment by sentanos** [comment]
Due to major changes in 3.0 this would have to be changed. Instead of messing with this other branch I will just add the function to 3.0 when I push it.

**Pull request closed without merging**
